name: polarity_Pylint

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Running Pytest and Pylint Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r polarity_check_api/requirements.txt
          python -c "import nltk; nltk.download('vader_lexicon')"

      - name: Running the UnitTest Cases
        run: |
          cd polarity_check_api
          python -m pytest ./tests

      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py') --rcfile=.pylintrc
          
